### ISSUE TITLE
Error when loading files with non-standard attributes

### ISSUE THREAD

**Issue by babiec** [NeurodataWithoutBorders/matnwb#245] opened 2020-12-21 20:08 UTC
I am using your matnwb suite to attempt to open the files in DANDI Archive 20 (https://gui.dandiarchive.org/#/dandiset/000020). More info can be found about the data in that archive here: https://portal.brain-map.org/explore/classes/multimodal-characterization/multimodal-characterization-mouse-visual-cortex. I was informed by the makers of the file (Allen Institute) that they were created using PyNWB 1.3.2 using NWB schema 2.2.5.

When I download a file in this set and attempt to read it using nwbRead(), I get the error message that I've included at the end of this file message. If I download files from another DANDI set created at a later date (DANDI Archive 50), the file reads just fine. I think this may have to do with migrating schema, but I don't know how to get access to older versions of the schema, so that I might figure this out. Any help would be greatly appreciated.

>> nwbRead('sub-605770584_ses-606098055_icephys.nwb')

ERROR MESSAGE

Array indices must be positive integers or logical values.

Error in file.fillExport (line 24)
    prop = pathProps{end};

Error in file.fillClass (line 93)
exporterFcns = file.fillExport(nonInherited, class, depnm);

Error in file.writeNamespace (line 22)
        fwrite(fid, file.fillClass(className, Namespace, processed, ...

Error in nwbRead>tryWriteSpec (line 106)
    file.writeNamespace(namespaceName);

Error in nwbRead>generateSpec (line 94)
    if ~tryWriteSpec(name)

Error in nwbRead>checkEmbeddedSpec (line 44)
    generateSpec(fid, h5info(filename, specLocation));

Error in nwbRead (line 27)
    specLocation = checkEmbeddedSpec(filename);

**Comment by ln-vidrio** [comment] 2020-12-23 17:16
I've fixed this specific error issue but am still unable to read the file normally due to a different error:
```
Error using h5infoc
UTF-8 encoding is only supported for variable length strings.

Error in h5info (line 108)
    hinfo = h5infoc(filename,location, useUtf8);

Error in nwbRead (line 33)
nwb = io.parseGroup(filename, h5info(filename), Blacklist);
```

For context: `h5info` is called to get a quick map of the HDF5 file and is used by matNWB to traverse the structure without loading data.
Looking at this with HDFView, it seems that some of the attributes in the dataset are storing the String with a static length using UTF-8, which apparently is not supported by `h5info`. I'm not entirely sure why this limitation exists but it does block further parsing of the data itself.

The only solution barring re-saving the file using variable length strings is to replace the `h5info` call and returned struct with low-level calls.

**Comment by rly** [comment] 2020-12-23 19:26
@ln-vidrio that is an odd limitation and if we can't work around it easily, we may have to impose restrictions on NWB files more broadly to disallow fixed length UTF-8-encoded strings.

Which file did you try to load? When I try running `h5info` on `sub-1001658946_ses-1003020741_icephys.nwb`, I do not get an error:
```matlab
>> h5info('sub-1001658946_ses-1003020741_icephys.nwb')

ans = 

  struct with fields:

      Filename: '/MATLAB Drive/sub-1001658946_ses-1003020741_icephys.nwb'
          Name: '/'
        Groups: [6×1 struct]
      Datasets: [5×1 struct]
     Datatypes: []
         Links: []
    Attributes: [5×1 struct]
```

**Comment by ln-vidrio** [comment] 2020-12-23 20:56
Try `sub-605770584_ses-606098055_icephys.nwb`

**Comment by rly** [comment] 2020-12-23 21:57
```matlab
>> h5info('sub-605770584_ses-606098055_icephys.nwb')

ans = 

  struct with fields:

      Filename: '/MATLAB Drive/sub-605770584_ses-606098055_icephys.nwb'
          Name: '/'
        Groups: [6×1 struct]
      Datasets: [5×1 struct]
     Datatypes: []
         Links: []
    Attributes: [5×1 struct]
```

Not sure why we're getting different results...

**Comment by ln-vidrio** [comment] 2020-12-23 22:34
@babiec This issue with h5info appears to have been fixed in MATLAB r2020b.

**Comment by babiec** [comment] 2020-12-23 23:09
OK. I just downloaded 2020B. I will give it a try. Do I need to update my matnwb?

**Comment by ln-vidrio** [comment] 2020-12-24 15:38
You should, that should fix the "array indices" error.

**Comment by babiec** [comment] 2020-12-25 02:37
Everybody, I really appreciate the efforts on this. I seem to be somewhere in between in the dialog above. I went through and downloaded the new matnwb, using git, so I could generateCore() successfully. I then went to open the file, I encountered a new error that seems to indicate things are getting closer (but not quite there). The exchange in MATLAB is below. I'm not sure why I got this and things worked for you all.

nwbRead('sub-605770584_ses-606098055_icephys.nwb')
Error using types.util.checkUnset (line 13)
Unexpected properties {data_IGORWaveNote data_IGORWaveScaling data_IGORWaveType
data_IGORWaveUnits}.

Your schema version may be incompatible with the file.  Consider checking the schema version
of the file with `util.getSchemaVersion(filename)` and comparing with the YAML namespace
version present in nwb-schema/core/nwb.namespace.yaml

Error in types.core.VoltageClampSeries (line 82)
            types.util.checkUnset(obj, unique(varargin(1:2:end)));

Error in io.parseGroup (line 85)
    parsed = eval([Type.typename '(kwargs{:})']);

Error in io.parseGroup (line 38)
    subg = io.parseGroup(filename, group, Blacklist);

Error in io.parseGroup (line 38)
    subg = io.parseGroup(filename, group, Blacklist);

Error in nwbRead (line 32)
nwb = io.parseGroup(filename, h5info(filename), Blacklist);

**Comment by ln-vidrio** [comment] 2020-12-28 16:29
This looks like a missing extension but I will take a look.

**Comment by ln-vidrio** [comment] 2020-12-28 16:41
So the VoltagClampSeries objects appear to have these extra IGOR attributes, which by default MatNWB does not accept without first making it an extension class. Are addable attributes a feature of pynwb @rly? This may need to be documented as well.

**Comment by oruebel** [comment] 2020-12-31 04:23
> MatNWB does not accept without first making it an extension class. Are addable attributes a feature of pynwb

PyNWB most likely just ignores those attributes on read, i.e., PyNWB can probably open those files but a user won't see those additional attributes. I believe the validator will probably issue warnings in this case.

**Comment by ln-vidrio** [comment] 2021-01-05 16:40
That's interesting, I can downgrade these missing fields to issue warnings instead of errors. This will allow reading data with extra fields but with the caveat that this data will never be seen and has a high chance of being silently deleted if the file were rewritten using MatNWB.

**Comment by oruebel** [comment] 2021-01-05 18:26
> ... can downgrade these missing fields to issue warnings instead of errors. This will allow reading data with extra fields

I have to admit I don't understand how missing fields relates to extra fields here. I think in general, missing fields can be errors and extra fields should be warnings. 

> with the caveat that this data will never be seen and has a high chance of being silently deleted if the file were rewritten using MatNWB.

I think that's fine. Extra fields not covered by an extension are not valid NWB, so the fact that those are not read/written by the API is valid behavior. Any additional fields not part of the standard must be governed by an extension. It will be useful to issue appropriate warnings for this to make sure users are aware of this behavior.

**Comment by oruebel** [comment] 2021-01-05 18:27
@rly @ajtritt can you confirm that PyNWB indeed behaves this way.

**Comment by ln-vidrio** [comment] 2021-01-05 19:57
I just haven't woken up yet, The "missing fields" should be read the same as "extra fields" as it's also missing from the schema.

**Comment by rly** [comment] 2021-01-05 23:18
> @rly @ajtritt can you confirm that PyNWB indeed behaves this way.

I can confirm that PyNWB ignores extra attributes, datasets, and groups. The validator currently does not raise warnings or errors, but see the chain of issues here for the current status of adding warnings for extra fields. https://github.com/NeurodataWithoutBorders/pynwb/issues/942

Interestingly, PyNWB does break when there are extra links. 

Sample code:
```python
from pynwb import NWBFile, NWBHDF5IO, validate
import datetime
import h5py


nwbfile = NWBFile(
    session_description='session_description',
    identifier='identifier',
    session_start_time=datetime.datetime.now(datetime.timezone.utc),
)

filename = 'nwbfile.nwb'

with NWBHDF5IO(filename, 'w') as io:
    io.write(nwbfile)

with h5py.File(filename, 'a') as f:
    f.create_group('extra_group')
    f.create_dataset('extra_dataset', (10,))
    f['session_description'].attrs['extra_attribute'] = 'my attribute'
    f.attrs['extra_attribute'] = 100
    # f['extra_dataset_link'] = f['session_description']
    # f['extra_group_link'] = f['stimulus']

with NWBHDF5IO(filename, 'r') as io:
    errors = validate(io)
    print(errors)
    nwbfile = io.read()
    print(nwbfile)
```

Output:
```
[]
root pynwb.file.NWBFile at 0x2651391859656
Fields:
  file_create_date: [datetime.datetime(2021, 1, 5, 15, 12, 42, 102979, tzinfo=tzoffset(None, -28800))]
  identifier: identifier
  session_description: session_description
  session_start_time: 2021-01-05 23:12:42.101976+00:00
  timestamps_reference_time: 2021-01-05 23:12:42.101976+00:00
```

**Comment by rly** [comment] 2021-01-05 23:35
To be clear, in the data file in question (`sub-605770584_ses-606098055_icephys.nwb` of DANDI Archive 20 gui.dandiarchive.org/#/dandiset/000020), the standard '/acquisition' and '/stimulus' groups contain `VoltageClampSeries` objects with a 'data' dataset that has four extra attributes: `IGORWaveNote`, `IGORWaveScaling`, `IGORWaveType`, and `IGORWaveUnits`. PyNWB does not raise a warning/error about these.

**Comment by rly** [comment] 2021-01-05 23:48
@t-b FYI in dandiset 20, which I think you wrote the output/conversion code for, the NWB files have extra attributes which are currently unreadable by MatNWB (though the errors will be changed to warnings, see above) and which will raise warnings in a future version of PyNWB and the PyNWB validator.

**Comment by t-b** [comment] 2021-01-06 13:18
@oruebel 

> I think that's fine. Extra fields not covered by an extension are not valid NWB, so the fact that those are not read/written by the API is valid behavior. Any additional fields not part of the standard must be governed by an extension. It will be useful to issue appropriate warnings for this to make sure users are aware of this behavior.

That definition would have been nice to have in the beginning, but this is not how things are currently. I can even not find that being mentioned in the nwb-schema documentation.

**Comment by oruebel** [comment] 2021-01-06 19:02
> That definition would have been nice

@t-b I agree that we need to clarify how we handle extra fields. So far, we have assumed that all fields in an NWB file are governed by the schema or an extension. Exposing extra fields that are not covered by an extension to the user through the APIs will be challenging and was one of the main issues we encountered in NWB 1.0. Ideally, however, I think we want to make sure that the APIs can still read such files (while ignoring extra fields) as long as the file includes all fields required by the schema.

**Comment by oruebel** [comment] 2021-01-06 19:18
For NWB I think there are a few items that we likely want to address in additional GitHub issues:

- Enhance the validator to warn on extra fields
- Update the documentation of PyNWB and MatNWB to describe explicitly how they handle extra fields not covered by the schema on read/write
- Update schema documentation to explicitly describe if extra fields are allowed and how they should be handled

**Comment by oruebel** [comment] 2021-01-08 05:11
@t-b  I've created the issue on PyNWB to enhance the validator https://github.com/NeurodataWithoutBorders/pynwb/issues/1332 . I've also created a PR on NWB schema to describe how extra fields should be handled https://github.com/NeurodataWithoutBorders/nwb-schema/pull/468 Please have a look at the text to see if that seems reasonable. 

I believe to resolve this issue, the main thing missing then is to implement the solution @In-vidrio described in MatNWB, i.e, 
*" ... downgrade the extra fields to issue warnings instead of errors. This will allow reading data with extra fields but with the caveat that this data will never be seen and has a high chance of being silently deleted if the file were rewritten using MatNWB."*

**Comment by rly** [comment] 2023-11-20 16:07
Hi @lawrence-mbf , could we prioritize resolving this issue using your solution above which @oruebel agrees with? I also think that that would work. This is blocking the read of at least 12 different dandisets -- all patchseq icephys data, all from the Allen Institute for Brain Science, I believe:

- DANDI:000020
- DANDI:000023
- DANDI:000043
- DANDI:000109
- DANDI:000142
- DANDI:000209
- DANDI:000288
- DANDI:000569
- DANDI:000570
- DANDI:000630
- DANDI:000635
- DANDI:000636

**Comment by oruebel** [comment] 2023-11-20 17:04
Yes, it would be good to prioritize this issue and the proposed solution sounds good.

**Comment by lawrence-mbf** [comment] 2023-11-20 22:00
Currently out of country, will get back to this in December.

Nov 21, 2023 01:05:14 Oliver Ruebel ***@***.***>:

**Closed** 2023-12-15 13:32 UTC
