### ISSUE TITLE
Property general_subject must be a types.ndx_icephys_meta.Subject

### ISSUE THREAD

**Issue by lvsltz** [NeurodataWithoutBorders/matnwb#202] opened 2020-04-09 17:23 UTC
Another error related to the `ndx_icephys_meta` extension:

Some example files are given in this drive folder, under **ndx_icephys_meta**.
https://drive.google.com/open?id=1HQPYqkV6zsyzFoG6qSnHXdkzV4a7HuV2

**ndx-bbp-icephys-hierarchy** contains the same data and additionally some extra groups in scratch created by [another extension](https://github.com/lvsltz/ndx-bbp-icephys-hierarchy).

**ndx_icephys_meta/001_140327B01_EXP_ndx.nwb** triggers the following error on nwbRead:

```matlab
Error using types.util.checkDtype (line 174)
Property `general_subject` must be a types.ndx_icephys_meta.Subject.

Error in types.ndx_icephys_meta.ICEphysFile/validate_general_subject (line 158)
        val = types.util.checkDtype('general_subject', 'types.ndx_icephys_meta.Subject', val);

Error in types.core.NWBFile/set.general_subject (line 288)
        obj.general_subject = obj.validate_general_subject(val);

Error in types.core.NWBFile (line 189)
        obj.general_subject = p.Results.general_subject;

Error in types.ndx_icephys_meta.ICEphysFile (line 24)
        obj = obj@types.core.NWBFile(varargin{:});

Error in io.parseGroup (line 80)
            parsed = eval([Type.typename '(kwargs{:})']);

Error in nwbRead (line 33)
nwb = io.parseGroup(filename, h5info(filename), Blacklist);
```

**Comment by ln-vidrio** [comment] 2020-04-09 22:20
This looks like a schema parsing incompatibility between MatNWB and PyNWB.  Because the generated schema used `neurodata_type_def` to define a `Subject` class while reading the `ndx_icephys_meta` namespace, MatNWB went ahead and defined its own Subject class under `types.ndx_icephys_meta` avoiding namespace conflicts that way.  PyNWB resolves the name conflict in the namespace by overwriting this type definition with the previous one found in `core`.  I'm sure there's more stuff checked by pynwb though, I'm not too sure how that part works.

In the meantime, the hacky way to fix this is to edit the `namespace` attribute of `/general/subject` and change it to `ndx-idcephys-meta` on the MatNWB side.  I can provide a script that fixes this but it will probably break compatibility in pynwb.

I will need to confirm if that is intended behavior on pynwb's part.

**Comment by lvsltz** [comment] 2020-04-10 07:36
Thanks for looking into this and the explanation. I think this types of errors will disappear once the extension is integrated in the schema. But until then, it'd be nice to be able to read the file to test the other functions of the extension. 
So for me, any temporary hack that allows reading is worth having.

**Comment by ln-vidrio** [comment] 2020-04-10 20:54
```
function edit_subject(filename)
fid = H5F.open(filename, 'H5F_ACC_RDWR', 'H5P_DEFAULT');
gid = H5G.open(fid, '/general/subject');
H5A.delete(gid, 'namespace');
io.writeAttribute(fid, '/general/subject/namespace', 'ndx-icephys-meta');
end
```
Copy the above into a MATLAB file and run it with a path to the file in question.  This requires MatNWB to be in the path for io.writeAttributes.

There will be another error from what I've seen but it's up to you if you wish to create a new ticket for it or not.  If so, I'll close this one.

**Comment by lvsltz** [comment] 2020-04-11 14:17
Thanks (and sorry, I thought you'd want to implement a hack it MatNWB, I could have done this manually :)
I didn't get any other error, so all good for now!

**Comment by ln-vidrio** [comment] 2020-04-13 14:28
Okay, post an issue if there is more!

**Closed by ln-vidrio** 2020-04-13 14:28 UTC

**Comment by rly** [comment] 2020-04-13 19:06
This was also an issue with PyNWB/HDMF reading and validating files generated with the ndx-icephys-meta extension. We are pushing a bug fix on the core NWB schema which will un-nest the `Subject` type from `NWBFile` (and also un-nest other nested types) to avoid this issue moving forward: https://github.com/NeurodataWithoutBorders/nwb-schema/pull/432
