### ISSUE TITLE
[Feature]: Use NWBInspector for Testing File validity

### ISSUE THREAD

**Issue by lawrence-mbf** [NeurodataWithoutBorders/matnwb#521] opened 2023-07-25 16:40 UTC
### What would you like to see added to MatNWB?

Using NWBInspector will allow for testing MatNWB compatibility to a greater degree since pynwb may not catch all configurations that may produce errors.

### What solution would you like?

Replace pynwb reads with nwbinspector calls

### Do you have any interest in helping implement the feature?

Yes.

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/neurodatawithoutborders/matnwb/blob/master/.github/CODE_OF_CONDUCT.md)
- [X] Have you ensured this change was not already [requested](https://github.com/NeurodataWithoutBorders/matnwb/issues)?

**Comment by ehennestad** [comment] 2024-10-31 14:15
@lawrence-mbf Was the idea to use the nwb inspector in the test suite?

**Comment by lawrence-mbf** [comment] 2024-10-31 14:19
Ideally, yes instead of the pynwb-based checks we have now. The nwb inspector will be more thorough since it will do more than just read and write checks.

**Comment by ehennestad** [comment] 2024-10-31 20:36
Closing this issue as a duplicate of #484

**Comment by ehennestad** [comment] 2024-10-31 20:36
Closing this issue as a duplicate of #484

**Closed by ehennestad** 2024-10-31 20:36 UTC
Labels: category: enhancement, topic: testing, status: todo
