### ISSUE TITLE
Error in opening example data and nwbtest

### ISSUE THREAD

**Issue by stevevanhooser** [NeurodataWithoutBorders/matnwb#208] opened 2020-04-28 15:33 UTC
I have 1) an error opening my first nwb file and 2)an error running nwbtest. I'm a new user so I might be doing something wrong.

I have installed matnwb and the nwb-schema and both are on my Matlab path. I have called generateCore().

Error 1 of 2): error opening example dataset
I downloaded a collection of datasets from the example datasets:
https://www.nwb.org/example-datasets/

Rutishauser Lab, Cedars Sinai, Human single-neuron activity during a declarative memory task
DOWNLOAD. Publication. Conversion code.

When I try to read it, I get an error:

n = nwbRead(‘P9HMH_NOID5.nwb’)
Undefined variable “types” or class “types.core.VectorData”.
Error in io.parseDataset (line 80)
    parsed = eval([Type.typename ’(kwargs{:})’]);

Error 2 of 2: I also tried running nwbtest and got an error. I assume this also indicates there is something wrong with my setup.

nwbtest
Error using fileparts
Too many input arguments.
Error in tests.Prep (line 26)
            [test_root, ~, ~] = fileparts(test_pkg_details.path);
Error in tests.TestConnection (line 1)
classdef TestConnection < tests.Prep
Error in tests.Main (line 1)
classdef Main < ...
Error in matlab.unittest.internal.TestCaseClassProvider/provideClassTestCase (line 62)
            testCase = constructTestCase();
Error in matlab.unittest.Test/provideClassTestCase (line 424)
            testCase = test.TestCaseProvider.provideClassTestCase;
Error in matlab.unittest.TestRunner/createTestClassInstance (line 1024)
            testCase = runner.TestRunData.CurrentSuite.provideClassTestCase;
Error in matlab.unittest.TestRunner/invokeTestContentOperatorMethod_ (line 908)
            [varargout{1:nargout}] = method(runner, pluginData);
<more of the stack here, I’ve truncated>

Thanks in advance
Steve

**Comment by ln-vidrio** [comment] 2020-04-28 15:41
I will investigate the first part of your question but the second part is very strange as it appears to be an internal MATLAB error.  What version of MATLAB are you using?

**Comment by stevevanhooser** [comment] 2020-04-28 15:43
Thanks! I run Matlab 2019a

Best
Steve

**Comment by stevevanhooser** [comment] 2020-04-28 15:44
The full error on nwbtest is:

nwbtest
Error using fileparts
Too many input arguments.

Error in tests.Prep (line 26)
            [test_root, ~, ~] = fileparts(test_pkg_details.path);

Error in tests.TestConnection (line 1)
classdef TestConnection < tests.Prep

Error in tests.Main (line 1)
classdef Main < ...

Error in matlab.unittest.internal.TestCaseClassProvider/provideClassTestCase (line 62)
            testCase = constructTestCase();

Error in matlab.unittest.Test/provideClassTestCase (line 424)
            testCase = test.TestCaseProvider.provideClassTestCase;

Error in matlab.unittest.TestRunner/createTestClassInstance (line 1024)
            testCase = runner.TestRunData.CurrentSuite.provideClassTestCase;

Error in matlab.unittest.TestRunner/invokeTestContentOperatorMethod_ (line 908)
            [varargout{1:nargout}] = method(runner, pluginData);

Error in matlab.unittest.plugins.TestRunnerPlugin/createTestClassInstance (line 465)
            testCase = iter.CurrentOperator.invokeTestContentOperatorMethod_(@createTestClassInstance, pluginData, iter);

Error in matlab.unittest.plugins.DiagnosticsOutputPlugin/createTestClassInstance (line 177)
            testCase = createTestClassInstance@matlab.unittest.plugins.TestRunnerPlugin(plugin, pluginData);

Error in matlab.unittest.plugins.TestRunnerPlugin/invokeTestContentOperatorMethod_ (line 686)
                [varargout{1:nargout}] = method(plugin, pluginData);

Error in matlab.unittest.plugins.TestRunnerPlugin/createTestClassInstance (line 465)
            testCase = iter.CurrentOperator.invokeTestContentOperatorMethod_(@createTestClassInstance, pluginData, iter);

Error in matlab.unittest.plugins.xml.JUnitXMLOutputPlugin/createTestClassInstance (line 111)
            testCase = createTestClassInstance@matlab.unittest.plugins.XMLPlugin(plugin, pluginData);

Error in matlab.unittest.plugins.TestRunnerPlugin/invokeTestContentOperatorMethod_ (line 686)
                [varargout{1:nargout}] = method(plugin, pluginData);

Error in matlab.unittest.TestRunner/evaluateMethodOnPlugins (line 758)
            [varargout{1:nargout}] = iter.CurrentOperator.invokeTestContentOperatorMethod_(method, pluginData, iter);

Error in matlab.unittest.TestRunner/prepareTestClass (line 592)
                classLevelTestCase = runner.evaluateMethodOnPlugins(@createTestClassInstance, runner.PluginData.createTestClassInstance);

Error in matlab.unittest.TestRunner/runSharedTestCase (line 429)
            runner.prepareTestClass(suite);

Error in matlab.unittest.TestRunner/runTestClass (line 1013)
                runner.runSharedTestCase(runner.PluginData.runSharedTestCase);

Error in matlab.unittest.TestRunner/invokeTestContentOperatorMethod_ (line 908)
            [varargout{1:nargout}] = method(runner, pluginData);

Error in matlab.unittest.TestRunner/evaluateMethodOnPlugins (line 758)
            [varargout{1:nargout}] = iter.CurrentOperator.invokeTestContentOperatorMethod_(method, pluginData, iter);

Error in matlab.unittest.TestRunner/runTestSuite (line 950)
                    runner.evaluateMethodOnPlugins(@runTestClass, runner.PluginData.runTestClass);

Error in matlab.unittest.TestRunner/invokeTestContentOperatorMethod_ (line 908)
            [varargout{1:nargout}] = method(runner, pluginData);

Error in matlab.unittest.plugins.TestRunnerPlugin/runTestSuite (line 226)
            iter.CurrentOperator.invokeTestContentOperatorMethod_(@runTestSuite, pluginData, iter);

Error in matlab.unittest.plugins.testrunprogress.TerseProgressPlugin/runTestSuite (line 29)
            runTestSuite@matlab.unittest.plugins.TestRunProgressPlugin(plugin, pluginData);

Error in matlab.unittest.plugins.TestRunnerPlugin/invokeTestContentOperatorMethod_ (line 686)
                [varargout{1:nargout}] = method(plugin, pluginData);

Error in matlab.unittest.plugins.TestRunnerPlugin/runTestSuite (line 226)
            iter.CurrentOperator.invokeTestContentOperatorMethod_(@runTestSuite, pluginData, iter);

Error in matlab.unittest.plugins.DiagnosticsOutputPlugin/runTestSuite (line 159)
            runTestSuite@matlab.unittest.plugins.TestRunnerPlugin(plugin, pluginData);

Error in matlab.unittest.plugins.TestRunnerPlugin/invokeTestContentOperatorMethod_ (line 686)
                [varargout{1:nargout}] = method(plugin, pluginData);

Error in matlab.unittest.plugins.TestRunnerPlugin/runTestSuite (line 226)
            iter.CurrentOperator.invokeTestContentOperatorMethod_(@runTestSuite, pluginData, iter);

Error in matlab.unittest.plugins.xml.JUnitXMLOutputPlugin/runTestSuite (line 101)
            plugin.runTestSuite@matlab.unittest.plugins.XMLPlugin(pluginData);

Error in matlab.unittest.plugins.TestRunnerPlugin/invokeTestContentOperatorMethod_ (line 686)
                [varargout{1:nargout}] = method(plugin, pluginData);

Error in matlab.unittest.plugins.TestRunnerPlugin/runTestSuite (line 226)
            iter.CurrentOperator.invokeTestContentOperatorMethod_(@runTestSuite, pluginData, iter);

Error in matlab.unittest.internal.plugins.CodeCoverageCollectionPlugin/runTestSuite (line 21)
            runTestSuite@matlab.unittest.plugins.TestRunnerPlugin(plugin, pluginData);

Error in matlab.unittest.plugins.TestRunnerPlugin/invokeTestContentOperatorMethod_ (line 686)
                [varargout{1:nargout}] = method(plugin, pluginData);

Error in matlab.unittest.TestRunner/evaluateMethodOnPlugins (line 758)
            [varargout{1:nargout}] = iter.CurrentOperator.invokeTestContentOperatorMethod_(method, pluginData, iter);

Error in matlab.unittest.TestRunner/doRun (line 414)
            runner.evaluateMethodOnPlugins(@runTestSuite, pluginData);

Error in matlab.unittest.TestRunner/run (line 293)
            result = doRun(runner);

Error in nwbtest (line 60)
  results = runner.run(suite);

ans =

     []

**Comment by ln-vidrio** [comment] 2020-04-28 15:51
It looks like that second part is related to https://www.mathworks.com/matlabcentral/answers/25236-fileparts-error
This is not reproducible for me and may indicate a problem with the MATLAB path pointing to an incorrect installation.  Can you type `path` in your MATLAB installation and confirm for me that the references to MATLAB internal functions are correct?  They're usually in the form of `...MATLAB/R2019a/toolbox...`

**Comment by ln-vidrio** [comment] 2020-04-28 15:52
Ah, actually this is complaining about too many input arguments.  Which just makes this weirder.  Regardless, I would like to verify that the MATLAB path is correct.

**Comment by ln-vidrio** [comment] 2020-04-28 16:19
As for the first question, the schema that was used to generate that dataset was MatNWB v0.2.1.  However, it does include `object_ids` which do not work with that version of MatNWB anyway.

https://www.dropbox.com/sh/k0kvr2gslrdphab/AABAzpTdzGdyWQZhc7ZoSiXHa?dl=0

I have attached two files in the dropbox link above:
1) *core.zip*, this contains the schema as was used in MatNWB for v0.2.1.  Unzip the contents into nwb-schema/core
2) *generateCore.m*: This modified generateCore removes the dependency on `hdmf_common` which was introduced after v0.2.1.  Replace this version with the one you have.  Make sure to keep a local copy of the original generateCore as you will need it for future MatNWB versions.

**Comment by stevevanhooser** [comment] 2020-04-28 17:19
Hi - 

Replacing those files allows me to open the files. Thanks! 

Thanks for looking into the nwbtest issue. I checked my MATLAB path and it is fine. My own test code for my lab's libraries works fine (tests thousands of lines of code) so everything in general is good I think. 

Ah, I see. I have several packages with tests folders and some of those are causing it to fail. There are various versions of KiloSort, spikedetekt2, and datajoint. 

The following:

`nwbtest('Name','tests.unit.*') `

succeeds.

Maybe ideal behavior should be restricting tests to nwb elements?

Best
Steve

**Comment by stevevanhooser** [comment] 2020-04-28 17:19
Thanks again for your help!

**Comment by ln-vidrio** [comment] 2020-04-28 18:25
I will consider doing so, though I've admittedly tended to treat the tests in `nwbtest` as a developer-facing test suite rather than a client-side test suite.  In the meantime, I will close this ticket as the main issue seems to be resolved.

Please let me know via a new ticket if other errors start cropping up.

**Closed by ln-vidrio** 2020-04-28 18:25 UTC
