### ISSUE TITLE
Error in nwbRead - Undefined variable "types" or class "types.hdmf_experimental.DynamicTableRegion".

### ISSUE THREAD

**Issue by ross-folkard** [NeurodataWithoutBorders/matnwb#304] opened 2021-08-26 13:29 UTC
Hi there, 

I generated a nwb file using the Spike Interface pipeline with  Jupyter notebook, where it can be successfully viewed with nwbWidgets. However, when I try to load the same file in to Matlab, it throws an error. This seems to only happen for files that contain Trigger data with spike times, as I am successfully able to load a nwb file without the trigger data and just spike times. 

Any help on the matter would be greatly appreciated, as I am much more comfortable working in Matlab compared with Python. 

Error: 
![image](https://user-images.githubusercontent.com/43117750/130970503-77542dab-3855-466b-bdd0-a592d7c14dfa.png)

Same File on Jupyter notebook with nwbWidgets:

![image](https://user-images.githubusercontent.com/43117750/130970802-ad026525-b551-4485-9ca3-4e7c26fe156a.png)

Same file minus Trigger Data:

![image](https://user-images.githubusercontent.com/43117750/130971255-8370a97d-1e9e-4d4e-98fd-5b7730043f89.png)

**Comment by rf13734** [comment] 2021-08-30 08:37
Hi @rly ,

I had no issues creating a nwb file with just spikes form the 'simple_bin' SI pipeline, but ran into issues with the ced_nwb_conversion_simple pipeline:


![image](https://user-images.githubusercontent.com/43117750/131310820-111efd1a-29c5-422b-a289-0d3162b5a5f9.png)

I'm using pynwb 2.5.1

![image](https://user-images.githubusercontent.com/43117750/131311082-cde83801-a9b8-4a39-a91f-017c457ed682.png)


I've shared the relevant files with @bendichter, maybe he can add you to the shared folder.

**Comment by bendichter** [comment] 2021-08-30 14:30
I have shared the data

**Comment by rly** [comment] 2021-08-30 17:23
Hi @rf13734 ,

It looks like you are using PyNWB 2.5.1, which is a broken and removed version of PyNWB (it was released with the wrong version tag). This version should not be downloadable from PyPI. How did you get it?

Can you please `pip uninstall pynwb` and then `pip install pynwb==2.0.0`, try to generate the file again, and let us know if the problem persists? Thanks in advance!

**Comment by lvsltz** [comment] 2021-08-30 19:53
> It looks like you are using PyNWB 2.5.1, which is a broken and removed version of PyNWB (it was released with the wrong version tag). This version should not be downloadable from PyPI. How did you get it?

Quick comment @rly: I've seen this as well multiple times just by doing `pip install pynwb`

**Comment by rly** [comment] 2021-08-31 07:05
Interesting. That's not great. I might have to delete the release or push 2.6 just so that becomes the largest version.
@lvsltz can you reproduce the behavior?

I've found that `pip install -U pynwb` with pip 20.3.1 would install the yanked version (incorrectly). See https://github.com/pypa/pip/issues/9290 but this is fixed now and @rf13734 is using pip 21.0.1 (at least currently).

**Comment by lvsltz** [comment] 2021-08-31 13:03
@rly I can't reproduce it. It was probably the old pip. Sorry for the diversion on this issue.

**Comment by rf13734** [comment] 2021-10-05 12:39
Apologies for the very late response, I installed pynwb 2.0
![image](https://user-images.githubusercontent.com/43117750/136023437-2609886f-4d7a-4892-a9d4-6435daa01bd0.png)

I'm now getting the following assertions error for this file:
![image](https://user-images.githubusercontent.com/43117750/136023732-6c11f815-f15d-4a49-be9e-e6fa4d22bc87.png)
![image](https://user-images.githubusercontent.com/43117750/136023802-c3265e45-eb26-481f-8964-5508bca7f240.png)

Any help would be greatly appreciated!

All the best

Ross

**Comment by bendichter** [comment] 2021-10-12 17:31
@rf13734 could you open an issue for this in https://github.com/catalystneuro/mease-lab-to-nwb? It looks like your file that we use to extract intervals has a different number of start and stop times for those intervals

**Closed as not planned** 2023-05-16 14:22 UTC
