### ISSUE TITLE
[Bug]: New matnwb not reading files

### ISSUE THREAD

**Issue by fsantamaria** [NeurodataWithoutBorders/matnwb#601] opened 2024-10-15 21:28 UTC
### What happened?

I upgraded matlab and downloaded the latest mantnwb (2.7.0). I added the path ($HOME/matnwb). When I type 
w=nwbRead('myfyle.nwb) I get this error. I have tried using gerneateExtensions for 2.7.0 and 2.6.0 (my files in older version), but maybe I'm doing this incorrectly . I use this to generateExtensions
generateExtension('$HOME/matnwb/nwb-schema/2.7.0/core/nwb.namespace.yaml').  Am I doing something wrong?

### Steps to Reproduce

```matlab
git clone https://github.com/NeurodataWithoutBorders/matnwb.git
In matlab
addpath()
w=nwbRead(myfile)
```

### Error Message

```matlab
Error using ind2sub (line 27)
Size vector must be a real vector with at least 2 elements.

Error in types.untyped.DataStub/load_mat_style (line 49)
        [points{:}] = ind2sub(dataDimensions, orderedSelection);
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Error in types.untyped.DataStub/load (line 124)
                data = obj.load_mat_style(varargin{1});
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Error in indexing (line 157)
                B = builtin('subsref', obj, S);
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^
Error in types.util.checkDtype>unwrapValue (line 162)
            unwrapped = wrapped.load(1);
                        ^^^^^^^^^^^^^^^
Error in types.util.checkDtype (line 123)
    value = unwrapValue(value);
            ^^^^^^^^^^^^^^^^^^
Error in types.core.NWBFile/validate_file_create_date (line 335)
        val = types.util.checkDtype('file_create_date', 'datetime', val);
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Error in types.core.NWBFile/set.file_create_date (line 187)
        obj.file_create_date = obj.validate_file_create_date(val);
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Error in types.core.NWBFile (line 127)
        obj.file_create_date = p.Results.file_create_date;
        ^^^^^^^^^^^^^^^^^^^^
Error in NwbFile (line 16)
            obj = obj@types.core.NWBFile(varargin{:});
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Error in io.parseGroup (line 76)
            parsed = NwbFile(kwargs{:});
                     ^^^^^^^^^^^^^^^^^^
Error in nwbRead (line 79)
    nwb = io.parseGroup(filename, h5info(filename), Blacklist);
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

### Operating System

Linux

### Matlab Version

2024b

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/neurodatawithoutborders/matnwb/blob/master/.github/CODE_OF_CONDUCT.md)
- [X] Have you ensured this bug was not already [reported](https://github.com/NeurodataWithoutBorders/matnwb/issues)?

**Comment by rly** [comment] 2024-10-15 21:39
Hi @fsantamaria, how did you (or someone else) generate the NWB file that you cannot read? Would it be possible for you to send us one of the files that generates this error? It would help us investigate the issue. The issue seems to be with validating the `file_create_date` value.

**Comment by fsantamaria** [comment] 2024-10-15 21:57
Hi,
Thanks for the quick reply. I just generated a file with a minimum of data points. FYI, I'm running simulations in Neuron Python and saving the results in nwb. Because of legacy issues and my expertise I then upload in matlab for analsyis.

Here's the file and just confirmed that generates the same error message.

Thanks for the help.

Best,
Fidel



--

Fidel Santamaria, PhD

Professor

Department of Neuroscience, Developmental and Regenerative Biology

One UTSA circle

University of Texas at San Antonio,

San Antonio, TX 78249

Office: (210) 458-6910

Lab: (210) 458-6982

Fax: (210) 458-5658

Office/Lab Location: BSB 1.03.30

http://www.utsa.edu/santamarialab/index.htm

________________________________
From: Ryan Ly ***@***.***>
Sent: Tuesday, October 15, 2024 4:40 PM
To: NeurodataWithoutBorders/matnwb ***@***.***>
Cc: Fidel Santamaria ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL] Re: [NeurodataWithoutBorders/matnwb] [Bug]: New matnwb not reading files (Issue #601)

  **EXTERNAL EMAIL**
  This email originated outside of The University of Texas at San Antonio.
  Please exercise caution when clicking on links or opening attachments.



Hi @fsantamaria<https://github.com/fsantamaria>, how did you (or someone else) generate the NWB file that you cannot read? Would it be possible for you to send us one of the files that generates this error? It would help us investigate the issue. The issue seems to be with validating the file_create_date value.

**Comment by fsantamaria** [comment] 2024-10-16 15:26
Hi,

I brought my previous version of matnwb (2.6.0) from my backup. Just copied it directly. It is able to read the files. Of course, it sends a warning when trying to read the recent files I created in python with 2.7.0.






--

Fidel Santamaria, PhD

Professor

Department of Neuroscience, Developmental and Regenerative Biology

One UTSA circle

University of Texas at San Antonio,

San Antonio, TX 78249

Office: (210) 458-6910

Lab: (210) 458-6982

Fax: (210) 458-5658

Office/Lab Location: BSB 1.03.30

http://www.utsa.edu/santamarialab/index.htm

________________________________
From: Ryan Ly ***@***.***>
Sent: Tuesday, October 15, 2024 4:40 PM
To: NeurodataWithoutBorders/matnwb ***@***.***>
Cc: Fidel Santamaria ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL] Re: [NeurodataWithoutBorders/matnwb] [Bug]: New matnwb not reading files (Issue #601)

  **EXTERNAL EMAIL**
  This email originated outside of The University of Texas at San Antonio.
  Please exercise caution when clicking on links or opening attachments.



Hi @fsantamaria<https://github.com/fsantamaria>, how did you (or someone else) generate the NWB file that you cannot read? Would it be possible for you to send us one of the files that generates this error? It would help us investigate the issue. The issue seems to be with validating the file_create_date value.

**Comment by ehennestad** [comment] 2024-10-16 18:10
Hi,

I am not able to find the file you attached. Is it possible to either upload the file to a google drive/dropbox and create a shared link ?

**Comment by fsantamaria** [comment] 2024-10-16 18:48
Let's try this
[https://res.cdn.office.net/assets/mail/file-icon/png/generic_16x16.png]Rpfcf_WT_test25b000.nwb<https://utsacloud-my.sharepoint.com/:u:/g/personal/fidel_santamaria_utsa_edu/EZ-nGV8HhEJOjlkrG_t8g-QBwT9f6Lfmg61l5Kh5-nWnqw?e=j7YEym>





--

Fidel Santamaria, PhD

Professor

Department of Neuroscience, Developmental and Regenerative Biology

One UTSA circle

University of Texas at San Antonio,

San Antonio, TX 78249

Office: (210) 458-6910

Lab: (210) 458-6982

Fax: (210) 458-5658

Office/Lab Location: BSB 1.03.30

http://www.utsa.edu/santamarialab/index.htm

________________________________

**Comment by ehennestad** [comment] 2024-10-16 19:15
Thanks for sharing the file!

I am able to open it in MATLAB R2023b, using both an older version of matnwb and the newest version from GitHub. However, I get the same error as you when I use MATLAB R2024b, and this is due to a breaking change in the ind2sub function introduced with MATLAB R2024. 

I unfortunately can not propose a fix right now, but will work on this tomorrow. In the mean time, you could try using an older release of MATLAB if this is available to you.

**Comment by fsantamaria** [comment] 2024-10-16 19:56
Thanks for figuring this out. I'll check if I can download an older version.




--

Fidel Santamaria, PhD

Professor

Department of Neuroscience, Developmental and Regenerative Biology

One UTSA circle

University of Texas at San Antonio,

San Antonio, TX 78249

Office: (210) 458-6910

Lab: (210) 458-6982

Fax: (210) 458-5658

Office/Lab Location: BSB 1.03.30

http://www.utsa.edu/santamarialab/index.htm

________________________________
From: ehennestad ***@***.***>
Sent: Wednesday, October 16, 2024 2:15 PM
To: NeurodataWithoutBorders/matnwb ***@***.***>
Cc: Fidel Santamaria ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL] Re: [NeurodataWithoutBorders/matnwb] [Bug]: New matnwb not reading files (Issue #601)

  **EXTERNAL EMAIL**
  This email originated outside of The University of Texas at San Antonio.
  Please exercise caution when clicking on links or opening attachments.



Thanks for sharing the file!

I am able to open it in MATLAB R2023b, using both an older version of matnwb and the newest version from GitHub. However, I get the same error as you when I use MATLAB R2024b, and this is due to a breaking change in the ind2sub function introduced with MATLAB R2024.

I unfortunately can not propose a fix right now, but will work on this tomorrow. In the mean time, you could try using an older release of MATLAB if this is available to you.

**Comment by fsantamaria** [comment] 2024-10-16 19:59
Sorry, forgot to mention. I am able to open the files in 2024b using the older version of matnwb (2.6.0). Hope this info helps.






--

Fidel Santamaria, PhD

Professor

Department of Neuroscience, Developmental and Regenerative Biology

One UTSA circle

University of Texas at San Antonio,

San Antonio, TX 78249

Office: (210) 458-6910

Lab: (210) 458-6982

Fax: (210) 458-5658

Office/Lab Location: BSB 1.03.30

http://www.utsa.edu/santamarialab/index.htm

________________________________
From: ehennestad ***@***.***>
Sent: Wednesday, October 16, 2024 2:15 PM
To: NeurodataWithoutBorders/matnwb ***@***.***>
Cc: Fidel Santamaria ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL] Re: [NeurodataWithoutBorders/matnwb] [Bug]: New matnwb not reading files (Issue #601)

  **EXTERNAL EMAIL**
  This email originated outside of The University of Texas at San Antonio.
  Please exercise caution when clicking on links or opening attachments.



Thanks for sharing the file!

I am able to open it in MATLAB R2023b, using both an older version of matnwb and the newest version from GitHub. However, I get the same error as you when I use MATLAB R2024b, and this is due to a breaking change in the ind2sub function introduced with MATLAB R2024.

I unfortunately can not propose a fix right now, but will work on this tomorrow. In the mean time, you could try using an older release of MATLAB if this is available to you.

**Comment by ehennestad** [comment] 2024-10-16 22:17
> Sorry, forgot to mention. I am able to open the files in 2024b using the older version of matnwb (2.6.0). Hope this info helps.

That is interesting. Did you use the exact same file? I tried the same, but for me this did not work (of course, I might have a different version of matnwb, but based on the error and the cause of the error I am curious to understand how you could open the file without error using an older version of matnwb).

I added a proposed fix on this branch:
https://github.com/NeurodataWithoutBorders/matnwb/tree/601-fix-ind2sub-with-scalar-size

You could try it out and let us know if it works. I will update you when this is merged to main.

**Comment by fsantamaria** [comment] 2024-10-28 15:39
Hi, yes, I used the same file that I sent you. Right now we're plowing ahead with 2023b.  The only piece of info is that when I used 2024b with nwb 2.6.0 I got a warning about the 2.7.0 schema of the new file. But the  data looked ok.

Best,


--

Fidel Santamaria, PhD

Professor

Department of Neuroscience, Developmental and Regenerative Biology

One UTSA circle

University of Texas at San Antonio,

San Antonio, TX 78249

Office: (210) 458-6910

Lab: (210) 458-6982

Fax: (210) 458-5658

Office/Lab Location: BSB 1.03.30

http://www.utsa.edu/santamarialab/index.htm

________________________________
From: ehennestad ***@***.***>
Sent: Wednesday, October 16, 2024 5:17 PM
To: NeurodataWithoutBorders/matnwb ***@***.***>
Cc: Fidel Santamaria ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL] Re: [NeurodataWithoutBorders/matnwb] [Bug]: New matnwb not reading files (Issue #601)

  **EXTERNAL EMAIL**
  This email originated outside of The University of Texas at San Antonio.
  Please exercise caution when clicking on links or opening attachments.



Sorry, forgot to mention. I am able to open the files in 2024b using the older version of matnwb (2.6.0). Hope this info helps.

That is interesting. Did you use the exact same file? I tried the same, but for me this did not work (of course, I might have a different version of matnwb, but based on the error and the cause of the error I am curious to understand how you could open the file without error using an older version of matnwb).

I added a proposed fix on this branch:

https://github.com/NeurodataWithoutBorders/matnwb/tree/601-fix-ind2sub-with-scalar-size

You could try it out and let us know if it works. I will update you when this is merged to main.

**Comment by ehennestad** [comment] 2024-10-31 14:44
> Hi, yes, I used the same file that I sent you. Right now we're plowing ahead with 2023b. The only piece of info is that when I used 2024b with nwb 2.6.0 I got a warning about the 2.7.0 schema of the new file. But the data looked ok.

The latest commit of matnwb does support nwb files created with v2.7.0, so you could try that if you find that your version of matnwb does not correctly handle v2.7.0 files

**Closed** 2024-11-04 19:28 UTC
Labels: category: bug, status: need verification
